### ISSUE TITLE
Wrong line break for `bat` file.

### ISSUE THREAD

**Issue by abcfy2** [alexeylisyutenko/windows-service-plugin#2]
Hi @alexeylisyutenko , this plugin is so awsome and I like it. But one thing is that the line break of `bat` script is wrong. Windows `bat` script must use `CRLF` as line break, but your script uses `LF`, so I can't run the script, I have to change the line break manully and run again.

Another thing is that will you plan to support custom environment variables? Link tomcat? Maybe it's useful.

**Comment by alexeylisyutenko** [comment]
Hi, Feng Yu.
Thank you for your feedback. Now when I see that the plugin is useful for
some people I'm determined to maintain it.
I'm going to add all the others options supported by procrun, fix your
issue and add some other functions soon. I guess I'll do it in a week,
maybe two.
Best regards, Alexey.

2017-11-17 11:47 GMT+03:00 Feng Yu <notifications@github.com>:

**Comment by alexeylisyutenko** [comment]
Fiexed in 1.1.0 release
